#ifndef LIBMQTTCLIENT_GLOBAL_H
#define LIBMQTTCLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBMQTTCLIENT_LIBRARY)
#  define LIBMQTTCLIENT_EXPORT Q_DECL_EXPORT
#else
#  define LIBMQTTCLIENT_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBMQTTCLIENT_GLOBAL_H
